theme: jekyll-theme-cayman
title: ASaP
description: Agent-based Smart Service Platform
show_downloads: "true"
github:
  zip_url: https://github.com/pioneo/product-asap/archive/v1.0.2.zip
  tar_url: https://github.com/pioneo/product-asap/archive/v1.0.2.tar.gz
  mac_url: https://github.com/pioneo/product-asap/releases/download/v1.0.2/mac.zip
